### ISSUE TITLE
NoCommentedOutCodeFixer removes urls

### ISSUE THREAD

**Issue by weshooper** [kubawerlos/php-cs-fixer-custom-fixers#129]
In the following example, the first line is removed by `NoCommentedOutCodeFixer`:

```
// http://edmondscommerce.github.io/php/barcode/ean13-barcode-check-digit-with-php.html
public static function checkDigit(string $barcode): int
```

**Comment by kubawerlos** [comment]
It _feels_ both - a bug and not a bug :)

In terms of PHP syntax `http://edmondscommerce.github.io/php/barcode/ean13-barcode-check-digit-with-php.html` is valid code - it's label followed by a colon and then comment `//edmondscommerce.github.io/php/barcode/ean13-barcode-check-digit-with-php.html`.

One solution is to add `@see` before the URL.

Other would be to use `filter_var` for comment content, but wouldn't that be having special case?

**Comment by weshooper** [comment]
@kubawerlos Aha, thanks for the reply (and these extra fixers!) - `@see` sounds like a good solution.
