### ISSUE TITLE
Removing usage of preg_quote broke PHP 7.2

### ISSUE THREAD

**Issue by nico-incubiq** [kubawerlos/php-cs-fixer-custom-fixers#172]
[This commit](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/commit/759dc576625725f12a202c1b7b629e52cd860c06) causes php 7.2.* to choke (tested on 7.2.19 and 7.2.23). Here's a simple bit of code i put together to reproduce:
```php
use PhpCsFixerCustomFixers\Fixer\PhpdocSelfAccessorFixer;

include_once('./vendor/autoload.php');

$reflection = new ReflectionClass(PhpdocSelfAccessorFixer::class);
$method = $reflection->getMethod('getNewContent');
$method->setAccessible(true);

$fixer = new PhpdocSelfAccessorFixer();
$method->invoke($fixer, '/**
     * @param string $message Error message.
     */', 'Nicolas\ErrorCatalogue', 'PublicException');
```
The error is: `PHP Warning:  preg_replace(): Compilation failed: unknown property name after \P or \p at offset 72`. Seems to come from the fact the quoting doesn't work properly, as the `\E` in `\ErrorCatalogue` is wrongly interpreted as the end of the quoting. This is fixed in PHP 7.3, but it might be easier to bring back `preg_quote` rather than releasing a new bugfix version of PHP 7.2.

**Comment by kubawerlos** [comment]
Thanks @nico-incubiq for the report, I've found a [case](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/174/files#diff-9aa1f58a0173181b0bc63343166cf1d7R205) that brakes each PHP version.
