### ISSUE TITLE
consider moving some to PHP-CS-Fixer itself

### ISSUE THREAD

**Issue by SpacePossum** [kubawerlos/php-cs-fixer-custom-fixers#30]
Awesome custom fixers, lot of good stuff :)
I was wondering `NoTwoConsecutiveEmptyLinesFixer`, is there something different than `no_extra_blank_lines` with config `extra`? Like to know if I missed something there.

`PhpdocVarAnnotationCorrectOrderFixer` please consider bringing this to PHP-CS-Fixer as well, love to have it in there :)

**Comment by kubawerlos** [comment]
Thanks. Absolutely, the whole idea for this repo is to avoid copy/pasting fixers between all my projects and have them here - some too specific (like `NoPhpStormGeneratedCommentFixer`) and some in "easy version" and when needed/requested/ready - move them to the main repo.

`NoTwoConsecutiveEmptyLinesFixer` does one more thing comparing to `no_extra_blank_lines`. It will remove an empty line from:
```php
<?php


$foo;
```
as `T_OPEN_TAG` will contain one `\n` and `no_extra_blank_lines` wont' count it - as I've checked that is the only case I was missing - should we fix it and deprecate `NoTwoConsecutiveEmptyLinesFixer`?

And `PhpdocVarAnnotationCorrectOrderFixer` is already in [PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3881).

**Comment by SpacePossum** [comment]
thanks man :)

> - as I've checked that is the only case I was missing - should we fix it 

to me that sounds like a true bug in the `no_extra_blank_lines` fixer
