### ISSUE TITLE
How can I use this with the php-cs-fixer PHAR?

### ISSUE THREAD

**Issue by mfn** [kubawerlos/php-cs-fixer-custom-fixers#368]
I prefer using php-cs-fixer PHAR as to not pull in all the dependencies for a tool supposed to not be integrated directly into my application, e.g. https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/bb9f72904497cea78b59faa3abeca21aaa5390a5/composer.json#L17-L32
```json
    "require": {
        "php": "^5.6 || ^7.0",
        "ext-json": "*",
        "ext-tokenizer": "*",
        "composer/semver": "^1.4 || ^2.0 || ^3.0",
        "composer/xdebug-handler": "^1.2",
        "doctrine/annotations": "^1.2",
        "php-cs-fixer/diff": "^1.3",
        "symfony/console": "^3.4.43 || ^4.4.11 || ^5.1.3",
        "symfony/event-dispatcher": "^3.0 || ^4.0 || ^5.0",
        "symfony/filesystem": "^3.0 || ^4.0 || ^5.0",
        "symfony/finder": "^3.0 || ^4.0 || ^5.0",
        "symfony/options-resolver": "^3.0 || ^4.0 || ^5.0",
        "symfony/polyfill-php70": "^1.0",
        "symfony/polyfill-php72": "^1.4",
        "symfony/process": "^3.0 || ^4.0 || ^5.0",
        "symfony/stopwatch": "^3.0 || ^4.0 || ^5.0"
    },
```

But then, how can I use this without having to install php-cs-fixer via composer 🤔

Thanks

**Comment by keradus** [comment]
for my knowledge - not really possible, at least not easily.
it's a nightmare - if we have PHP CS Fixer phar, with dependencies locked inside, and then we would have, eg custom fixers phar, dependencies locked inside, how to ensure that those dependencies are compatible?

btw, if your project, like `mfn/foo`, would install `php-cs-fixer` under `require-dev`, the main dependencies of `php-cs-fixer`, configured in`required` section, eg `composer/xdebug-handler`, will be treated as `dev` dependency for `mfn/foo` and if you `composer install --no-dev` on your `mfn/foo` project, the `xdebug-handler` won't be installed.

**Comment by mfn** [comment]
>  it's a nightmare - if we have PHP CS Fixer phar, with dependencies locked inside, and then we would have, eg custom fixers phar, dependencies locked inside, how to ensure that those dependencies are compatible?

Thanks, I thought so. Too bad.

_Personally_ I would rather use the awesome fixers and wouldn't _necessary_ need a guarantee that this works. If it breaks, I'll see it anyway ;) But obviously that's against the spirit of proper versioning and dependencies.

**Comment by kubawerlos** [comment]
Thanks @keradus,

I was trying to find a solution as well, but haven't found any, no library (like [phpunit-speedtrap](https://github.com/johnkary/phpunit-speedtrap)) can do this.
