### ISSUE TITLE
Expand NoUselessCommentFixer to remove more cases

### ISSUE THREAD

**Issue by Bilge** [kubawerlos/php-cs-fixer-custom-fixers#630]
Where the class name is duplicated into the comment, it is not always prefixed with _Class_, as in the following examples.

```diff
/**
- * Foo.
 */
 class Foo
```

```diff
/**
- * Bar
 */
 class Bar
```

**Comment by kubawerlos** [comment]
I will do the release during the weekend. One more thing - I want to add support for greater/less assertions to PhpUnitAssertArgumentsOrderFixer.
