### ISSUE TITLE
CommentSurroundedBySpacesFixer error

### ISSUE THREAD

**Issue by volovodenko** [kubawerlos/php-cs-fixer-custom-fixers#716]
CommentSurroundedBySpacesFixer error when docblock type hint exists

With type hint
![2022-01-14 11-18-48](https://user-images.githubusercontent.com/29176940/149492249-be7451a8-77d4-4faa-9da5-5a1c1e5ef92d.png)

Without type hint
![2022-01-14 11-19-06](https://user-images.githubusercontent.com/29176940/149492307-f66db66f-43b2-48e7-9ba1-ebd036fc20a7.png)

**Comment by volovodenko** [comment]
![Снимок экрана от 2022-01-14 11-36-28](https://user-images.githubusercontent.com/29176940/149493367-e81ad8a5-1429-4de5-8822-5cd0ac4e2a19.png)

![Снимок экрана от 2022-01-14 11-34-22](https://user-images.githubusercontent.com/29176940/149493404-036b1bc5-c17e-46b3-8c3f-c8ff1ee806e9.png)

![Без имени](https://user-images.githubusercontent.com/29176940/149493444-beedde2d-50f3-4583-8b73-65c08d38424f.png)

**Comment by Bilge** [comment]
This happens after upgrading PHP-CS-Fixer from 3.4 -> 3.5.

**Comment by kubawerlos** [comment]
@volovodenko @Bilge fixed and released, thanks for reporting.
