### ISSUE TITLE
BC-break in DataProviderStaticFixer

### ISSUE THREAD

**Issue by tjveldhuizen** [kubawerlos/php-cs-fixer-custom-fixers#746]
Since version 3.8.0, when I don't modify my configuration file, I get the following exception. As far as I can see, [this modification in `isRisky()`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/commit/a3d990eb25bf9bc952784b27076bffdc1d481f1f#diff-6d0e2484b146175d22249a168d81c234d69c6962b6462f57a0539c7f79f70c9aL55-L58) always sets 'risky' to true and can not be changed.

```
In ConfigurationResolver.php line 349:

  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  The rules contain risky fixers ("PhpCsFixerCustomFixers/data_provider_static"), but they are not allowed to run. Perhaps you forget to use --allow-risky=yes option?
```

**Comment by kubawerlos** [comment]
I'm not sure that this counts as BC break - boolean value returned from method was changed, but [this](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/747) improvement will solve the problem.

**Comment by tjveldhuizen** [comment]
After the upgrade to 3.8.0 (automatic, by [Renovatebot](https://github.com/renovatebot/renovate)), without any other customization, the CI-pipeline is failing. There seems to be no way to fix it, except disabling this fixer or enabling risky fixes in general. I think that should count as a BC-break.
