### ISSUE TITLE
Request: empty method to single line

### ISSUE THREAD

**Issue by onet4** [kubawerlos/php-cs-fixer-custom-fixers#748]
Hello, 

I have a request.

I'd like to make the following code. 

```php
    public function test()
    {
    }
```
to

```php
    public function test() {}
```

,similar to `ConstructorEmptyBracesFixer`, as the former takes too much space. Would be appreciated if you could create one for such a case. 

Thank you for your consideration.

**Comment by kubawerlos** [comment]
I wonder what about these cases:
```php
function a(): void
{
}
function b(
    int $x
)
{
}
```
not mentioning other cases.

Maybe it is worth raising a discussion in a main repo.

**Comment by onet4** [comment]
I'd like to see them being converted to:
```php
function a(): void {}
function b( int $x ) {}
```
