### ISSUE TITLE
Help in the installation of  "php-cs-fixer-custom-fixers".

### ISSUE THREAD

**Issue by nateriver74** [kubawerlos/php-cs-fixer-custom-fixers#755]
Hello everyone,
I'm a bit of a novice at this and I wish you could help me, I want to install the "php-cs-fixer-custom-fixers" package in VSCODE, the problem is that I don't know how to do it.
I don't know if I should install it in a particular directory or how I should configure it to make use of its rules.
I am in a "Windows 10" operating system, I have "Git bash version 2.35", "Composer version 2.2.7" and "junstyle.php-cs-fixer-0.2.10" installed, the latter configured as follows:

```php
<?php
// ...
    return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR2'                   => true,
        'align_multiline_comment' => ['comment_type' => 'all_multiline'],
        'array_indentation'       => true,
        'array_syntax'            => ['syntax' => 'short'],
        'binary_operator_spaces'  => [
        .
        .
```
From already thank you very much!

**Comment by kubawerlos** [comment]
Hi,

are you able to to autoload the classes by adding e.g. `require_once __DIR__ . '/vendor/autoload.php';` above the return?

Then you can `registerCustomFixers` and use them in `setRules` as usual.
