### ISSUE TITLE
`PhpdocArrayStyleFixer` breaks PHPStorm-friendly traversable info

### ISSUE THREAD

**Issue by Wirone** [kubawerlos/php-cs-fixer-custom-fixers#840]
Imagine scenario:

```php
/**
 * @template T
 * @implements IteratorAggregate<int, T>
 */
class TypedCollection implements IteratorAggregate {}

/**
 * @extends TypedCollection<Foo>
 */
class FooCollection extends TypedCollection {}
```

Then, if we use `FooCollection|Foo[]` somewhere (because without `|Foo[]` [PHPStorm's autocompletion does not work](https://twitter.com/_Codito_/status/1592299907075145729)), `PhpdocArrayStyleFixer` breaks the static analysis because it changes type to `FooCollection|array<Foo>` which is wrong. It is described in [PHPStan's documentation](https://phpstan.org/writing-php-code/phpdoc-types#iterables):

> If PHPStan encounters `Collection|Foo[]`, two possible paths are taken:
>
> - `Collection` implements `Traversable` so `Collection|Foo[]` is interpreted as a `Collection` object that iterates over `Foo`. The array part isn’t applied.
> - `Collection` does not implement `Traversable` so `Collection|Foo[]` is interpreted as a `Collection` object or an array of `Foo` objects.

## Expected behavior:

`PhpdocArrayStyleFixer` should change `smth[]` into `array<smth>` only if it's not helper type for traversable objects.

**Comment by kubawerlos** [comment]
I'm confused why `Collection|Foo[]` is ambiguous (@ondrejmirtes is there any reason for such behavior?).
If one means a collection of objects why not simply use `Collection<Foo>`?

In [PSR-5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#abnf) `[]` is clearly defined as an array.

**Comment by ondrejmirtes** [comment]
`Collection|Foo[]` was popular back in the old days (think when NetBeans was the popular IDE) to mean `Collection of Foo`. So when PHPStan sees `Collection|Foo[]` and `Collection` is iterable, it does this.

Yeah, I'd like to not use this syntax anymore, but it's out there so PHPStan needs to understand this. To disambiguate it to mean "Collection or array", you can do `Collection|array<Foo>`.

It's described in the docs: https://phpstan.org/writing-php-code/phpdoc-types#iterables

**Comment by Wirone** [comment]
FYI: it was [fixed in PHPStorm](https://youtrack.jetbrains.com/issue/WI-69717/Missing-generics-metadata-for-iterator-but-only-on-specific-scenarios), I just checked on our codebase and there's valid autocomplete even after removing `|Foo[]` part. In our case we need to get rid of that legacy union type, so feel free to close this if you don't feel the need to provide such improvement 😉.

For now we have clone of your fixer with additional condition in the `fixType()` method:

```php
// CHANGED: Do not touch complex types (e.g. `FooCollection|Foo[]`)
if (strpos($type, '|') !== false || strpos($type, '&') !== false) {
    return $type;
}
```
