### ISSUE TITLE
MultilinePromotedPropertiesFixer: Fix only with at least 2 arguments

### ISSUE THREAD

**Issue by shyim** [kubawerlos/php-cs-fixer-custom-fixers#862]
Hey,

We want to use `MultilinePromotedPropertiesFixer`, but it seems to format also just one argument. It would be nice if that could be configured.

**Comment by kubawerlos** [comment]
@shyim can you take a look at https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/869 ? Any better idea for the option name? Or some more test cases?
