### ISSUE TITLE
`MultilinePromotedPropertiesFixer`: keep blank lines between properties

### ISSUE THREAD

**Issue by gharlan** [kubawerlos/php-cs-fixer-custom-fixers#873]
I have some classes with long descriptions on each property:

```php
class Foo
{
    public function __construct(
        /**
         * Here long
         * description
         */
        public string $a,

        /**
         * Here long
         * description
         */
        public string $b,

        /**
         * Here long
         * description
         */
        public string $c,
    ) {}
}
```

The `MultilinePromotedPropertiesFixer` removes the blank lines between these properties.

What do you prefer?
1. Keep it as it is
2. never remove blank lines, only ensure that there is at least one line break between promoted properties
3. add a new config for this

**Comment by gharlan** [comment]
If you are ok with 2 or 3, I would like to create a pull request for this.

**Comment by kubawerlos** [comment]
Hi @gharlan, in the config approach do you mean to decide whether to remove a blank line or keep it?

**Comment by gharlan** [comment]
Yes, e.g. `keep_blank_lines`

**Comment by kubawerlos** [comment]
Sounds like a nice enhancement, go for it 👍🏼
