### ISSUE TITLE
ConstructorEmptyBracesFixer no longer works on 3.19.2 version

### ISSUE THREAD

**Issue by X-Coder264** [kubawerlos/php-cs-fixer-custom-fixers#905]
On 3.19.1 the ConstructorEmptyBracesFixer fixer works as expected. Updating CS fixer to 3.19.2 causes our CI pipeline to fail as it tries to update all constructor single lines back to the multi line syntax which is not expected behavior.

```diff
 <?php
 class Foo {
     public function __construct(
         $param1,
         $param2
-    ) {}
+    ) {
+    }
 }
```

**Comment by kubawerlos** [comment]
Hi @X-Coder264, is it fixed in [latest](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/releases/tag/v3.15.0) release?

**Comment by X-Coder264** [comment]
@kubawerlos It is. Thank you for the quick fix and tag.
