### ISSUE TITLE
StringableInterfaceFixer rule adds unnecessary Stringable to implements list

### ISSUE THREAD

**Issue by Arkemlar** [kubawerlos/php-cs-fixer-custom-fixers#923]
I have Interface A:
```php
use App\PhpExtension\EqualityInterface;
use JsonSerializable;
use Stringable;

interface Money extends JsonSerializable, Stringable, EqualityInterface
{
}
```
and class that implements it:
```php
class MoneyWrapper implements Money
{
}
```
and php-cs-fixer with config:
```
    ->setRules([
        ...
        PhpCsFixerCustomFixers\Fixer\StringableInterfaceFixer::name() => true,
    ])
```

Now when I run `php-cs-fixer fix` it changes my class to this:
```php
use Stringable;

class MoneyWrapper implements Money, Stringable
{
}
```

This is wrong behaivor, it must not add Stringable to the class since interface it implements already extends from Stringable.

**Comment by Arkemlar** [comment]
And IDE shows me reasonable error
![изображение](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/assets/19671202/71baab65-fe47-41f4-a4a6-71786fce5931)

**Comment by kubawerlos** [comment]
Hi @Arkemlar,

PHP CS Fixer works on a per-file basis and cannot determine what are the relations between interfaces outside of the file it is currently fixing, thus it is not possible to discover the situation you have described.

Moreover, this is not a bug, it is a false positive of PHPStorm: https://youtrack.jetbrains.com/issue/WI-50862

As it was reported 4 years ago and is still not fixed I've actually have an idea, take a look at https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/926

**Comment by Arkemlar** [comment]
@kubawerlos Thank you for fix, could you please explain how it works?

**Comment by kubawerlos** [comment]
Well, since there is actually no bug, there is not really a fix for it.

The improvement is exactly what the title of https://github.com/kubawerlos/php-cs-fixer-custom-fixers/pull/926 says.
